name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Run unit tests
        run: |
          poetry run pytest

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/${{ matrix.architecture }} -t ghcr.io/${{ github.repository }}/sample-api:latest --push .

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: |
          docker tag ghcr.io/${{ github.repository }}/sample-api:latest ghcr.io/${{ github.repository }}/sample-api:latest
          docker push ghcr.io/${{ github.repository }}/sample-api:latest